# Generated by Django 5.1.2 on 2024-10-23 03:24

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_chefresponsibility_chef'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The name of the recipe.', max_length=100, verbose_name='Name')),
                (
                    'description',
                    models.TextField(
                        blank=True, help_text='Description of the recipe.', null=True, verbose_name='Description'
                    ),
                ),
                ('ingredients', models.TextField(help_text='Ingredients of the recipe', verbose_name='Ingredients')),
                (
                    'preparation_method',
                    models.TextField(help_text='Preparation method of the recipe', verbose_name='Preparation Method'),
                ),
                (
                    'servings',
                    models.IntegerField(
                        default=1,
                        help_text='Servings of the recipe',
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=1, message='Servings must be equal to or greater than 1.'
                            )
                        ],
                        verbose_name='Servings',
                    ),
                ),
                (
                    'prep_time',
                    models.DurationField(
                        help_text='Preparation time of the recipe',
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=datetime.timedelta(seconds=60),
                                message='Preparation time must be equal to or greater than 1 minute.',
                            )
                        ],
                        verbose_name='Prep Time',
                    ),
                ),
                (
                    'cook_time',
                    models.DurationField(
                        help_text='Cooking time of the recipe',
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=datetime.timedelta(0),
                                message='Cooking time must be equal to or greater than 0 minutes.',
                            )
                        ],
                        verbose_name='Cook Time',
                    ),
                ),
                (
                    'is_public',
                    models.BooleanField(
                        default=False, help_text='Whether the recipe is public or not.', verbose_name='Is Public'
                    ),
                ),
                (
                    'chef',
                    models.ForeignKey(
                        help_text='The chef of the recipe.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='recipes',
                        to='user.chef',
                        verbose_name='Chef',
                    ),
                ),
                (
                    'shared_with',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Chefs with whom the recipe is shared.',
                        related_name='shared_recipes',
                        to='user.chef',
                        verbose_name='Shared With',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
        ),
    ]
