# Generated by Django 5.1.2 on 2024-10-23 22:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.DurationField(
                blank=True,
                help_text='Cooking time of the recipe',
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.timedelta(0),
                        message='Cooking time must be equal to or greater than 0 minutes.',
                    )
                ],
                verbose_name='Cook Time',
            ),
        ),
    ]
